title: Learning The Grid
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.234767
  brandStrength: 0
  rhythmicContrast: 0.3028674
  brandColors:
    - '#ffffff'
    - '#7c7761'
    - '#1d2621'
    - '#42453a'
    - '#b8b8b8'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: LearningTheGrid
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5
layout_spectrum: 0.2455197
