name: LearningTheGrid
favicon: null
layout_spectrum: 0.59627
typography_spectrum: 0.2744363497477025
title: Learning The Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7c7761'
    - '#1d2621'
    - '#42453a'
    - '#b8b8b8'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.7497606799006462
  rhythmicContrast: 0.75
purpose: []
