name: LearningTheGrid
favicon: null
layout_spectrum: 0
typography_spectrum: 0.2744363497477025
title: Learning The Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.44368077139370143
  lightness: 0.9088717026170343
  saturation: 0.7497606799006462
  rhythmicContrast: 0.066358178621158
purpose: []
